# Generated by Django 3.0.8 on 2020-07-25 16:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200725_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.CharField(max_length=500),
        ),
    ]
